import { type post_mod_T } from '@rappstack/domain--any--blog/post'
export const post_mod_a1:post_mod_T[] = await Promise.all([
	import('./content/altitude-training.js'),
	import('./content/anti-aging-and-life-extension-therapy.js'),
	import('./content/comprehensive-wellness-testing-and-screening.js'),
	import('./content/epidural-neoregeneration.js'),
	import('./content/exercise-with-detox-therapy.js'),
	import('./content/exercise-with-ketamine-infusion-therapy.js'),
	import('./content/exercise-with-oxygen-therapy.js'),
	import('./content/full-body-scan-with-low-dose-radiation.js'),
	import('./content/genetic-testing.js'),
	import('./content/hyperbaric-oxygen-therapy.js'),
	import('./content/infrared-and-red-light-therapy.js'),
	import('./content/intercostal-nerve-block.js'),
	import('./content/joint-saving-therapy.js'),
	import('./content/myers-cocktail-with-nad-and-glutathione.js'),
	import('./content/naltrexone-implants.js'),
	import('./content/performance-improvement.js'),
	import('./content/psychedelic-therapy.js'),
])
