import { spinal_cord_stimulation } from '@btakita/domain--server--peakexistence/feature'
import { sticky_h2__dl_tree_props_ } from '@btakita/ui--server--peakexistence/sticky'
import { post_meta__validate } from '@rappstack/domain--server--blog/post'
import { tb_a_ } from '@rappstack/ui--any/anchor'
import { dl_tree_ } from '@rappstack/ui--any/dl'
import { md__raw_ } from '@rappstack/ui--any/md'
import { nl } from '@rappstack/ui--any/string'
import { footnote__sup_, footnote__sup__sort } from '@rappstack/ui--server--blog/footnote'
import { type request_ctx_T } from 'rebuildjs/server'
import { mobile_hidden__span_ } from '../../responsive/index.js'
export const meta_ = (ctx:request_ctx_T)=>post_meta__validate(ctx, {
	pub_date: '2024-03-22T20:42:15.614Z',
	...spinal_cord_stimulation,
	title: 'Spinal Cord Stimulation: Managing Chronic Pain with Electrical Impulses',
	description: `Chronic pain, particularly in the back & limbs, can be debilitating for sufferers. Often leading to significant reductions in quality of life & functional ability. Traditional treatments such as medications, physical therapy, or surgery may not provide relief. Leaving patients in continuous discomfort. Spinal cord stimulation (SCS) emerges as a solution for pain management. Offering hope & substantial pain relief for those with chronic pain conditions.`,
})

// @formatter:off
// language=md
export default (ctx:request_ctx_T)=>''
+ md__raw_({ ctx },
	`Spinal Cord Stimulation (SCS) is a pain relief technique that delivers low-level electrical impulses. Directly to the spinal cord. These impulses are generated by a small device implanted under the skin. Typically near the buttocks or abdomen. Transmitting impulses via leads placed in the epidural space of the spine. SCS is designed to interrupt pain signals before they reach the brain. Masking the sensation of pain with a more pleasant tingling feeling known as paresthesia. In some cases, no sensation at all${footnote__sup__sort([/*ref1_footnote__sup_(ctx),*/ref5_footnote__sup_(ctx),ref9_footnote__sup_(ctx),/*ref13_footnote__sup_(ctx),*/ref15_footnote__sup_(ctx),ref19_footnote__sup_(ctx)])}.`)
+	dl_tree_({ ctx, _: sticky_h2__dl_tree_props_ }, ()=>[
	[`## ${mobile_hidden__span_([`Understanding `])}How SCS Works`, ()=>[
		[`### Device Components`, [
			`The SCS system consists of:`,
			()=>[
				[`#### Generator`, [
					`A small, battery-powered device surgically implanted under the skin. Typically, in the abdomen or buttock.`,]],
				[`#### Leads`, [
					`Thin, insulated wires with electrodes at the tip. Placed near the spinal cord within the epidural space.`,]],
				[`#### Remote Control`, [
					`A handheld device allows you to turn the system on & off. And adjust stimulation settings like intensity & pulse patterns.`,]],],]],
		[`### Masking Pain Signals`, [
			`The electrical pulses delivered by the SCS system aim to create a tingling sensation. That helps to override or mask pain signals traveling to your brain. The exact mechanism isn't fully understood. It may involve influencing how the nervous system processes pain.`,]],
		[`### ${mobile_hidden__span_([`What Is Known About the `])}Mechanism of SCS`, [
			`The exact mechanism of Spinal Cord Stimulation (SCS) is not fully understood. Research has made significant progress in elucidating the mechanisms behind SCS. The specific pathways & processes involved remain partially hypothetical & elusive. Research has identified multiple potential mechanisms at both the spinal & supraspinal levels. Including${footnote__sup__sort([ref3_1_footnote__sup_(ctx),ref3_2_footnote__sup_(ctx),ref3_5_footnote__sup_(ctx)])}:`,
			`- the modulation of wide dynamic range (WDR) neurons`,
			`- increased release of inhibitory neurotransmitters like GABA`,
			`- changes in the excitatory & inhibitory balance within the spinal cord`,
			nl,
			`Different SCS modalities may engage distinct mechanisms to achieve pain relief. Such as tonic & burst stimulation${footnote__sup__sort([ref3_3_footnote__sup_(ctx),ref3_5_footnote__sup_(ctx)])}.`,
			nl,
			`The complexity of pain pathways. And individual variability in response to SCS therapy. Make an ongoing challenge of fully understanding its mechanism of action.`,]],]],
	[`## The SCS Procedure`, [
		`The SCS procedure typically involves two stages${footnote__sup__sort([ref7_footnote__sup_(ctx),ref9_footnote__sup_(ctx)/*,ref13_footnote__sup_(ctx)*/])}:`,
		()=>[
			[`### Evaluation`, [
				`A thorough assessment with a pain specialist determines if SCS is a suitable option. This includes medical history, physical exam, imaging, & often a psychological evaluation.`,]],
			[`### Trial Period`, [
				`Before permanent implantation, a temporary trial is conducted. Connecting leads without a surgical incision to an external generator worn on a belt. To test the effectiveness of the device. Success is usually defined as a 50% or greater reduction in pain. This trial phase lasts about a week. Allowing the patient & doctor to evaluate the effectiveness of the stimulation settings. Gauging how well you respond to the therapy.`,]],
			[`### Permanent Implantation`, [
				`If the trial is successful, a permanent device is implanted. Through a minimally invasive surgical procedure. To implant the generator & leads to their final position.`,]],
			[`### Programming & Optimization`, [
				`Your doctor works with you to find the optimal stimulation settings. That provides the best pain relief & minimize any side effects. Adjusting the device's settings according to your pain management needs over time.`,]],],]],
	[`## Applications for ${mobile_hidden__span_([`Spinal Cord Stimulation`, `SCS`])}`, [
		`SCS is most commonly used for chronic pain conditions. That has not responded to more conservative treatments. It is often considered a last resort when other therapies. Such as medication, physical therapy, or surgery, have failed. Conditions commonly treated with SCS include:`,
		()=>[
			[`### Chronic back, neck, & limb pain`, [
				`Especially in cases where surgery has not relieved pain.`,]],
			[`### Neuropathic Pain`, [
				`Such as pain resulting from nerve damage in conditions like diabetic neuropathy or shingles.`,]],
			[`### Complex Regional Pain Syndrome (CRPS)`, [
				`CRPS is a chronic condition affecting a limb. Usually after injury, causing burning pain, swelling, & skin changes.`,]],
			[`### Peripheral Neuropathy`, [
				`Nerve damage often in the legs & feet due to conditions like diabetes or chemotherapy.`,]],
			[`### Radiculopathy`, [
				`Pain radiating down the leg due to a compressed spinal nerve root.`,]],
			[`### Arachnoiditis`, [
				`Inflammation & scarring of the protective layers of the spinal nerves.`,]],
			[`### Failed Back Surgery Syndrome (FBSS)`, [
				`FBSS is a persistent pain following one or more spine surgeries. Also known as post-laminectomy syndrome.`,]],
			[`### Visceral Abdominal & Perineal Pain`, [
				`${footnote__sup__sort([ref1_footnote__sup_(ctx),ref5_footnote__sup_(ctx),ref9_footnote__sup_(ctx)/*,ref16_footnote__sup_(ctx)*/])}`,]],
			[`### Other Causes`, [
				`Other cases may be conidered, such as:`,
				`- intractable back & leg pain`,
				`- phantom limb pain`,
				`- pain after spinal cord injury`,]],],]],
	[`## Benefits${mobile_hidden__span_([` of Spinal Cord Stimulation`])}`, [
		`SCS offers several advantages over traditional pain management methods:`,
		()=>[
			[`### Targeted Pain Relief`, [
				`SCS delivers relief directly to the area of pain. Without the systemic side effects of oral medications${ref6_footnote__sup_(ctx)}.`,]],
			[`### Increased Mobility`, [
				`Reduction in pain can improve mobility & overall quality of life.`,]],
			[`### Adjustable Therapy`, [
				`Stimulation settings can be remotely adjusted. Increased or decreased in intensity & modulation. To meet individual pain relief needs${footnote__sup__sort([ref6_footnote__sup_(ctx),ref7_footnote__sup_(ctx)])}.`,]],
			[`### Reversible Procedure`, [
				`Unlike many surgical interventions for chronic pain, SCS is reversible. The device can be turned off or surgically removed if desired.`,]],
			[`### Reduced Medication Use`, [
				`SCS can reduce the need for pharmaceutical pain medications, including opioids. helping patients avoid the side effects associated with long-term use of pain medications${ref6_footnote__sup_(ctx)}<!--ref13_footnote__sup_(ctx)-->.`,]],
			[`### Improved Quality of Life`, [
				`Patients often report${ref15_footnote__sup_(ctx)}:`,
				`- better sleep`,
				`- increased activity levels`,
				`- an improvement in quality of life`,]],],]],
	[`## Considerations, Risks, & Complications`, [
		`While SCS is generally safe, it carries potential risks & complications, including:`,
		()=>[
			[`### Not a Cure`, [
				`SCS is primarily focused on symptom management, not curing the underlying condition.`,]],
			[`### Infection`, [
				`As with any surgical procedure, there is a risk of infection.`,]],
			[`### Variability in Effectiveness`, [
				`The degree of pain relief can vary between people. Open communication with your pain specialist is essential for realistic expectations.`,]],
			[`### Potential Risks`, [
				`As with any implanted device, risks include:`,
				`- infection`,
				`- Bleeding`,
				`- Nerve damage`,
				`- Lead migration or breakage`,
				`- battery failure`,
				`- need for surgical revision`,
				`- Device malfunction${footnote__sup__sort([ref4_footnote__sup_(ctx),ref11_footnote__sup_(ctx)])}`,]],],]],
	[`## Controversies & Considerations`, [
		`Recent reviews have cast doubt on the long-term efficacy of SCS. A Cochrane Review concluded that SCS provides no better relief than a placebo for treating low back pain. With little to no benefit for improving quality of life. The review also highlighted the lack of long-term data. And poorly documented adverse side effects. Suggesting that the benefits of SCS may not outweigh the costs & risks${footnote__sup__sort([/*ref2_footnote__sup_(ctx),*/ref3_footnote__sup_(ctx)])}.`,
		nl,
		`Despite these concerns, many patients & clinicians report positive outcomes with SCS. The therapy remains a viable option for those with intractable chronic pain. The field of neuromodulation is rapidly evolving. With newer devices & technologies offering improved outcomes${footnote__sup__sort([ref5_footnote__sup_(ctx),ref8_footnote__sup_(ctx)/*,ref13_footnote__sup_(ctx)*/])}.`,]],
	[`## The Future of ${mobile_hidden__span_([`Spinal Cord Stimulation`, `SCS`])}`, [
		`Advancements in technology continue. Enhancing the effectiveness & usability of spinal cord stimulation devices. Recent developments include:`,
		nl,
		`- rechargeable systems with longer life spans`,
		`- more precise targeting of electrical impulses`,
		`- using sub-perception stimulation techniques that do not produce the tingling sensation of paresthesia`,
		nl,
		()=>[
			[`### Improving Modulation Protocols`, [
				`Advances in SCS technology include the development of various new stimulation patterns & waveforms. Designed to enhance pain relief & patient outcomes. For example, time-dynamic pulse modulation using novel patterns. Such as stochastic rate modulation & sinusoidal rate modulation. It has shown improved analgesia in preclinical studies${ref1_1_footnote__sup_(ctx)}. Additionally, the emergence of paresthesia-free or subperception stimulation patterns. Such as Differential Target Multiplexed (DTM) stimulation & fast-acting subperception therapy (FAST). Offers alternatives to conventional tonic stimulation & may be more effective in certain cases${ref1_4_footnote__sup_(ctx)}.`,
				nl,
				`The use of improved modulation protocols with existing devices. Depends on the specific device & its capabilities. Newer SCS systems are programmable & adaptable. Allowing for updates & the use of novel waveforms${footnote__sup__sort([ref1_2_footnote__sup_(ctx),ref1_3_footnote__sup_(ctx)])}. For instance, devices that include feature capabilities can include these modulation adjustments${ref1_9_footnote__sup_(ctx)}:`,
				`- high-frequency stimulation`,
				`- burst stimulation`,
				`- other novel waveforms`,
				nl,
				`Not all existing devices may be compatible with the latest modulation protocols. Using improved modulation protocols requires that the device's hardware & software support these updates. If an implanted device does not support the new protocols. A device upgrade or replacement may be necessary. To take advantage of the latest advancements in SCS therapy${footnote__sup__sort([ref1_2_footnote__sup_(ctx),ref1_3_footnote__sup_(ctx)])}.`,]],
			[`### SCS for Other Conditions`, [
				()=>[
					[`#### Refractory Angina`, [
						`Research indicates SCS as an effective & safe treatment option. With clinical trials & systematic reviews demonstrating its efficacy in providing${footnote__sup__sort([ref2_1_footnote__sup_(ctx),ref2_2_footnote__sup_(ctx),ref2_3_footnote__sup_(ctx),ref2_5_footnote__sup_(ctx),ref2_7_footnote__sup_(ctx),ref2_8_footnote__sup_(ctx),ref2_13_footnote__sup_(ctx),ref2_15_footnote__sup_(ctx)])}:`,
						`- symptomatic relief`,
						`- functional status improvement`,
						`- enhanced quality of life for patient`,
						nl,
						`Authoritative institutions have recognized SCS as a therapeutic alternative to refractory angina. With class IIb recommendations${footnote__sup__sort([ref2_1_footnote__sup_(ctx),ref2_2_footnote__sup_(ctx)])}:`,
						`- American College of Cardiology`,
						`- American Heart Association`,
						`- European Society of Cardiology`,
						nl,
						`The mechanism of action for the anti-anginal & anti-ischemic effects of SCS may include${ref2_1_footnote__sup_(ctx)}:`,
						`- direct pain blocking`,
						`- reduced oxygen consumption`,
						`- decreased sympathetic tone`,
						`- redistribution of myocardial blood flow`,
						`- modulation of intracardiac neurons`,]],
					[`#### Gastrointestinal Disorders`, [
						`Studies have explored the use of SCS for Gastrointestinal conditions such as${footnote__sup__sort([ref2_4_footnote__sup_(ctx)/*,ref2_6_footnote__sup_(ctx)*/,ref2_9_footnote__sup_(ctx),ref2_10_footnote__sup_(ctx),ref2_11_footnote__sup_(ctx),ref2_12_footnote__sup_(ctx),ref2_14_footnote__sup_(ctx),ref2_16_footnote__sup_(ctx)])}:`,
						`- chronic nausea`,
						`- vomiting`,
						`- refractory abdominal pain`,
						`- gastroparesis`,
						nl,
						`Research suggests that SCS can improve gastric motility & accelerate gastric emptying. By inhibiting sympathetic activity${footnote__sup__sort([ref2_6_footnote__sup_(ctx),ref2_10_footnote__sup_(ctx)])}. Clinical trials have shown that SCS can lead to significant improvements in${footnote__sup__sort([ref2_4_footnote__sup_(ctx),ref2_9_footnote__sup_(ctx),ref2_11_footnote__sup_(ctx),ref2_12_footnote__sup_(ctx)])}:`,
						`- abdominal pain`,
						`- nausea`,
						`- vomiting`,
						`- reduced opioid requirements in patients with these conditions`,
						nl,
						`The pain relief mechanism involves activation of inhibitory dorsal horn cells & autonomic modulation${ref2_9_footnote__sup_(ctx)}.`,]],],]],],]],
	[`## The Takeaway`, [
		`Spinal cord stimulation provides a powerful addition to the range of chronic pain management options. If unrelenting pain disrupts your life & other treatments have fallen short. Discuss with a qualified pain management specialist whether SCS might be a potential avenue to explore. For improved quality of life.`,]],
	[`## Conclusion`, [
		`Spinal Cord Stimulation represents a significant development in the field of pain management. Particularly for patients with chronic pain conditions unresponsive to other treatments. The therapy continues to provide relief for many patients. While some recent studies question its long-term efficacy. As with any medical intervention. Have a thorough evaluation & discussion of potential risks & benefits with a healthcare provider. To determine if SCS is an appropriate treatment option.`,]],
])
// @formatter:on
function ref1_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'weillcornell'
	}, [
		tb_a_({
			href: 'https://comprehensivespine.weillcornell.org/treatments/spinal-cord-stimulation-and-what-conditions-it-can-treat/',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation & What Conditions It Can Treat')
	])
}
// function ref2_footnote__sup_(ctx:request_ctx_T) {
// 	return footnote__sup_({
// 		ctx,
// 		id: 'sydney'
// 	}, [
// 		tb_a_({
// 			href: 'https://www.sydney.edu.au/news-opinion/news/2023/03/07/spinal-cord-stimulation-doesn-t-help-with-back-pain-says-new-rev.html',
// 			nofollow: true,
// 			wrap: true,
// 		}, 'Spinal cord stimulation doesn\'t help with back pain, says new review')
// 	])
// }
function ref3_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'cochrane'
	}, [
		tb_a_({
			href: 'https://www.cochrane.org/news/spinal-cord-stimulation-doesnt-help-back-pain-says-new-review',
			nofollow: true,
			wrap: true,
		}, 'Spinal cord stimulation doesn’t help with back pain, says new review')
	])
}
function ref4_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'spine-health4'
	}, [
		tb_a_({
			href: 'https://www.spine-health.com/treatment/pain-management/disadvantages-and-risks-spinal-cord-stimulation',
			nofollow: true,
			wrap: true,
		}, 'Disadvantages and Risks of Spinal Cord Stimulation')
	])
}
function ref5_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'hss'
	}, [
		tb_a_({
			href: 'https://www.hss.edu/conditions_spinal-cord-stimulation-treatment-alternative-chronic-pain.asp',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulator – A Compelling Treatment Technique for Chronic Pain')
	])
}
function ref6_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'spine-health6'
	}, [
		tb_a_({
			href: 'https://www.spine-health.com/treatment/pain-management/advantages-spinal-cord-stimulation',
			nofollow: true,
			wrap: true,
		}, 'Advantages of Spinal Cord Stimulation')
	])
}
function ref7_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'spine-health7'
	}, [
		tb_a_({
			href: 'https://www.spine-health.com/treatment/pain-management/spinal-cord-stimulation-procedure',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation Procedure')
	])
}
function ref8_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'springer8'
	}, [
		tb_a_({
			href: 'https://link.springer.com/article/10.1007/s40122-021-00287-4',
			nofollow: true,
			wrap: true,
		}, 'Efficacy and Safety of 10 kHz Spinal Cord Stimulation Using Cervical and Thoracic Leads: A Single-Center Retrospective Experience')
	])
}
function ref9_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'ucsfhealth'
	}, [
		tb_a_({
			href: 'https://www.ucsfhealth.org/treatments/spinal-cord-stimulation',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation (ucsf)')
	])
}
function ref11_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nih11'
	}, [
		tb_a_({
			href: 'https://www.ncbi.nlm.nih.gov/books/NBK553154/',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation (nih)')
	])
}
// function ref13_footnote__sup_(ctx:request_ctx_T) {
// 	return footnote__sup_({
// 		ctx,
// 		id: 'mainlinespine'
// 	}, [
// 		tb_a_({
// 			href: 'https://mainlinespine.com/treatments-procedures/spinal-cord-stimulator/',
// 			nofollow: true,
// 			wrap: true,
// 		}, 'Spinal Cord Stimulator')
// 	])
// }
function ref15_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'hopkinsmedicine'
	}, [
		tb_a_({
			href: 'https://www.hopkinsmedicine.org/health/treatment-tests-and-therapies/treating-pain-with-spinal-cord-stimulators',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulator')
	])
}
// function ref16_footnote__sup_(ctx:request_ctx_T) {
// 	return footnote__sup_({
// 		ctx,
// 		id: 'thepaincenterinc'
// 	}, [
// 		tb_a_({
// 			href: 'https://thepaincenterinc.com/Blog/ArticleID/1040/What-Conditions-Can-a-Spinal-Cord-Stimulator-Treat',
// 			nofollow: true,
// 			wrap: true,
// 		}, 'What Conditions Can a Spinal Cord Stimulator Treat?')
// 	])
// }
function ref19_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'bostonscientific'
	}, [
		tb_a_({
			href: 'https://www.bostonscientific.com/en-US/patients-caregivers/device-support/scs/how-scs-works.html',
			nofollow: true,
			wrap: true,
		}, 'How Spinal Cord Stimulator systems work')
	])
}
function ref1_1_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nature'
	}, [
		tb_a_({
			href: 'https://www.nature.com/articles/s41598-020-77212-w',
			nofollow: true,
			wrap: true,
		}, 'Time-dynamic pulse modulation of spinal cord stimulation reduces mechanical hypersensitivity and spontaneous pain in rats')
	])
}
function ref1_2_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nih1_2'
	}, [
		tb_a_({
			href: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9951889/',
			nofollow: true,
			wrap: true,
		}, 'Advances in Spinal Cord Stimulation')
	])
}
function ref1_3_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nih1_3'
	}, [
		tb_a_({
			href: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10301664/',
			nofollow: true,
			wrap: true,
		}, 'Advances in Spinal Cord Neuromodulation: The Integration of Neuroengineering, Computational Approaches, and Innovative Conceptual Frameworks')
	])
}
function ref1_4_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'biomedcentral1_4'
	}, [
		tb_a_({
			href: 'https://trialsjournal.biomedcentral.com/articles/10.1186/s13063-023-07637-x',
			nofollow: true,
			wrap: true,
		}, 'Efficacy of the latest new stimulation patterns of spinal cord stimulation for intractable neuropathic pain compared to conventional stimulation: study protocol for a clinical trial')
	])
}
function ref1_9_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'lww1_9'
	}, [
		tb_a_({
			href: 'https://journals.lww.com/ijpn/fulltext/2023/37030/best_practice_recommendations_for_implantable.3.aspx',
			nofollow: true,
			wrap: true,
		}, 'Best Practice Recommendations for Implantable Neuromodulation Therapies for Pain: Spinal Cord Stimulation')
	])
}
function ref2_1_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nih2_1'
	}, [
		tb_a_({
			href: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3324738/',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation for Refractory Angina Pectoris -A Case Report-')
	])
}
function ref2_2_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'bjcardio'
	}, [
		tb_a_({
			href: 'https://bjcardio.co.uk/2016/07/spinal-cord-stimulation-for-refractory-angina-100-case-experience-from-the-national-refractory-angina-service/',
			nofollow: true,
			wrap: true,
		}, 'Spinal cord stimulation for refractory angina: 100 case-experience from the National Refractory Angina Service')
	])
}
function ref2_3_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nih2_3'
	}, [
		tb_a_({
			href: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5417578/',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation for Refractory Angina Pectoris')
	])
}
function ref2_4_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'springer2_4'
	}, [
		tb_a_({
			href: 'https://link.springer.com/article/10.1007/s10620-021-06896-5',
			nofollow: true,
			wrap: true,
		}, 'Effects of Spinal Cord Stimulation in Patients with Chronic Nausea, Vomiting, and Refractory Abdominal Pain')
	])
}
function ref2_5_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'neuromodulation'
	}, [
		tb_a_({
			href: 'https://www.neuromodulation.com/fact_sheet_angina',
			nofollow: true,
			wrap: true,
		}, 'Chronic Angina Pectoris')
	])
}
// Retracted
function ref2_6_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nih2_6'
	}, [
		tb_a_({
			href: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6955191/',
			nofollow: true,
			wrap: true,
		}, 'A Novel Approach in Spinal Cord Stimulation for Enhancing Gastric Motility: A Preliminary Study on Canines')
	])
}
function ref2_7_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'oup'
	}, [
		tb_a_({
			href: 'https://academic.oup.com/ehjopen/article/3/1/oeac083/6957334',
			nofollow: true,
			wrap: true,
		}, 'Neuromodulation in patients with refractory angina pectoris: a review')
	])
}
function ref2_8_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'springer2_8'
	}, [
		tb_a_({
			href: 'https://link.springer.com/article/10.1007/s12471-020-01422-0',
			nofollow: true,
			wrap: true,
		}, 'Improvement in quality of life and angina pectoris: 1-year follow-up of patients with refractory angina pectoris and spinal cord stimulation')
	])
}
function ref2_9_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'lww2_9'
	}, [
		tb_a_({
			href: 'https://journals.lww.com/ctg/fulltext/2020/02000/treatment_of_chronic_abdominal_pain_with_10_khz.3.aspx',
			nofollow: true,
			wrap: true,
		}, 'Treatment of Chronic Abdominal Pain With 10-kHz Spinal Cord Stimulation: Safety and Efficacy Results From a 12-Month Prospective, Multicenter, Feasibility Study')
	])
}
function ref2_10_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nih2_10'
	}, [
		tb_a_({
			href: 'https://pubmed.ncbi.nlm.nih.gov/24341686/',
			nofollow: true,
			wrap: true,
		}, 'Therapeutic potential of spinal cord stimulation for gastrointestinal motility disorders: a preliminary rodent study')
	])
}
function ref2_11_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'q4cdn'
	}, [
		tb_a_({
			href: 'https://s28.q4cdn.com/260621474/files/doc_downloads/outcomes/2020/08/Treatment-of-Chronic-Abdominal-Pain-With-10-kHz-Spinal-Cord-Stimulation-Results-From-a-12-Month-Prospective-Multicenter-Feasibility-Study.pdf',
			nofollow: true,
			wrap: true,
		}, 'Treatment of Chronic Abdominal Pain With 10-kHz Spinal Cord Stimulation: Safety and Efficacy Results From a 12-Month Prospective, Multicenter, Feasibility Study')
	])
}
function ref2_12_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'sciencedirect2_12'
	}, [
		tb_a_({
			href: 'https://www.sciencedirect.com/science/article/abs/pii/S1094715911601670',
			nofollow: true,
			wrap: true,
		}, 'Application of Spinal Cord Stimulation for the Treatment of Abdominal Visceral Pain Syndromes: Case Reports')
	])
}
function ref2_13_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'wiley'
	}, [
		tb_a_({
			href: 'https://onlinelibrary.wiley.com/doi/full/10.1002/clc.24016',
			nofollow: true,
			wrap: true,
		}, 'Design and rationale of the efficacy of spinal cord stimulation in patients with refractory angina pectoris (SCRAP) trial')
	])
}
function ref2_14_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'researchgate'
	}, [
		tb_a_({
			href: 'https://www.researchgate.net/publication/51861488_Spinal_Cord_Stimulation_Reverses_Pain_and_Diarrheal_Episodes_of_Irritable_Bowel_Syndrome_A_Case_Report',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation Reverses Pain and Diarrheal Episodes of Irritable Bowel Syndrome: A Case Report')
	])
}
function ref2_15_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'jpsmjournal'
	}, [
		tb_a_({
			href: 'https://www.jpsmjournal.com/article/S0885-3924%2805%2900676-7/fulltext',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation for the Management of Refractory Angina Pectoris')
	])
}
function ref2_16_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'sciencedirect2_16'
	}, [
		tb_a_({
			href: 'https://www.sciencedirect.com/science/article/abs/pii/S1094715911602833',
			nofollow: true,
			wrap: true,
		}, 'Spinal Cord Stimulation Reverses Pain and Diarrheal Episodes of Irritable Bowel Syndrome: A Case Report')
	])
}
function ref3_1_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'oup3_1'
	}, [
		tb_a_({
			href: 'https://academic.oup.com/painmedicine/article/20/Supplement_1/S13/5509436',
			nofollow: true,
			wrap: true,
		}, 'Mechanism of Action in Burst Spinal Cord Stimulation: Review and Recent Advances')
	])
}
function ref3_2_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'nih3_2'
	}, [
		tb_a_({
			href: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6491991/',
			nofollow: true,
			wrap: true,
		}, 'Mechanisms of spinal cord stimulation for the treatment of pain: Still in the dark after 50 years')
	])
}
function ref3_3_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'lww3_3'
	}, [
		tb_a_({
			href: 'https://journals.lww.com/pain/fulltext/2020/09001/spinal_cord_stimulation_in_chronic_neuropathic.11.aspx',
			nofollow: true,
			wrap: true,
		}, 'Spinal cord stimulation in chronic neuropathic pain: mechanisms of action, new locations, new paradigms')
	])
}
function ref3_5_footnote__sup_(ctx:request_ctx_T) {
	return footnote__sup_({
		ctx,
		id: 'biomedcentral3_5'
	}, [
		tb_a_({
			href: 'https://bioelecmed.biomedcentral.com/articles/10.1186/s42234-019-0023-1',
			nofollow: true,
			wrap: true,
		}, 'Spinal cord stimulation in chronic pain: evidence and theory for mechanisms of action')
	])
}
